### ISSUE TITLE
Not compatible with the version of your running IDE (GoLand 2022.3) Compatible with IntelliJ IDEA (Ultimate, Community, Educational), Android Studio and 12 more

### ISSUE THREAD

**Issue by crazygang-ai** [arhont375/intellij-thrift#2]
hi, i have a question:
Not compatible with the version of your running IDE (GoLand 2022.3)
Compatible with IntelliJ IDEA (Ultimate, Community, Educational), Android Studio and 12 more

my golang version:
<img width="442" alt="image" src="https://user-images.githubusercontent.com/18746703/211517547-5c37367b-d7ee-4cba-894b-2f870acb0e55.png">

**Comment by crazygang-ai** [comment]
it should be goland, not golang, sorry

**Comment by arhont375** [comment]
I don't have goland, but version that you using should be supported.
Some times passed since your question, let me know if problem wasn't resolved.
