### ISSUE TITLE
Not worked on latest GoLand

### ISSUE THREAD

**Issue by Gaojianli** [arhont375/intellij-thrift#21]
<img width="426" alt="image" src="https://github.com/arhont375/intellij-thrift/assets/19235246/264d3b0c-6a32-43a8-b782-bd1914b66c24">
<img width="355" alt="image" src="https://github.com/arhont375/intellij-thrift/assets/19235246/5bf7333e-91a6-4c30-adb6-4ed7d503126f">

The `1.7.0` of this plugin required `233.11799.241`, but the latest GoLand is only `233.11799.228`

**Comment by Elvis-Zhou** [comment]
the same error
